### ISSUE TITLE
Any screenshots?

### ISSUE THREAD

**Issue by aljawaid** [biblibre/kanboard-plugin-TaskNotificationIcon#2]
Hello, any screenshots on what this plugin does or where it shows up? or is it abandoned?

**Comment by jajm** [comment]
Hello,

Yes, this plugin is abandoned. I will make it clear in the README and archive this repository.

**Comment by aljawaid** [comment]
Pass iton tome, let me try to revive it and and release aversion into the kanboard plugins directory. It would be a shame to waste your hard work, if it is functional

**Comment by jajm** [comment]
You can fork the repository and list your fork into the kanboard plugins directory. What else do you need ?
